spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/internet_monitoring
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

iums:
  dataset-path: data/sessions.csv
